version: "3.8"
services:
  app1:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379  
    env_file: .env

  app2:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379  
    env_file: .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "8088:88"
    depends_on:
      - app1
      - app2

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kagarwal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
